// import type { Metadata } from 'next'

// export default {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
//   // authors: [ { name: '{{{ COMPANY_NAME }}}', url: '' } ],
//   creator: '{{{ COMPANY_NAME }}}',
//   applicationName: '{{{ PRODUCT_NAME }}}',
//   // themeColor: '{{{ BACKGROUND_COLOR }}}',
//   themeColor: [
//     { media: "(prefers-color-scheme: dark)", color: "#000000" },
//     { media: "(prefers-color-scheme: light)", color: "#ffffff" }
//   ],
//   // colorScheme : 'normal',
//   viewport: {
//     width: '{{{ WIDTH }}}',
//     height: '{{{ HEIGHT }}}',
//   },
//   other: {
//     productVersion: '{{{ PRODUCT_VERSION }}}',
//     splashScreenStyle: '{{{ SPLASH_SCREEN_STYLE }}}',
//     unityVersion: '{{{ UNITY_VERSION }}}',
//     developmentPlayer: '{{{ DEVELOPMENT_PLAYER }}}',
//     decompressionFallback: '{{{ DECOMPRESSION_FALLBACK }}}',
//     // initialMemory: "{{_{INITIAL_MEMORY}}}",
//     useWasm: '{{{ USE_WASM }}}',
//     useThreads: '{{{ USE_THREADS }}}',
//     useWebGl10: '{{{ USE_WEBGL_1_0 }}}',
//     useWebGl20: '{{{ USE_WEBGL_2_0 }}}',
//     useDataCaching: '{{{ USE_DATA_CACHING }}}',
//     loaderFilename: '{{{ LOADER_FILENAME }}}',
//     dataFilename: '{{{ DATA_FILENAME }}}',
//     frameworkFilename: '{{{ FRAMEWORK_FILENAME }}}',
//     codeFilename: '{{{ CODE_FILENAME }}}',
//     memoryFilename: '{{{ MEMORY_FILENAME }}}',
//     symbolsFilename: '{{{ SYMBOLS_FILENAME }}}',
//     backgroundFilename: '{{{ BACKGROUND_FILENAME }}}',
//   },
// } as Metadata
